languageCode = "zh-CN"
languageName = "简体中文"
weight = 1
title = "Gentoo 中文社区"

[params]
  displayName = "简体中文"
  isoCode = "zh-CN"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "img/genchu.png"
  description = "Gentoo 中文社区官方网站"

[params.author]
  name = "Gentoo 中文社区"
  image = "img/genchu.png"
  links = [
    { github = "https://github.com/gentoo-zh" }
  ]
