languageCode = "zh-TW"
languageName = "繁體中文"
weight = 2
title = "Gentoo 中文社群"

[params]
  displayName = "繁體中文"
  isoCode = "zh-TW"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "img/genchu.png"
  description = "Gentoo 中文社群官方網站"

[params.author]
  name = "Gentoo 中文社群"
  image = "img/genchu.png"
  links = [
    { github = "https://github.com/gentoo-zh" }
  ]
