[[main]]
  name = "下载"
  pageRef = "/download"
  weight = 10

[[main]]
  name = "Overlay"
  pageRef = "/overlay"
  weight = 20

[[main]]
  name = "镜像列表"
  pageRef = "/mirrorlist"
  weight = 30

[[main]]
  name = "关于"
  pageRef = "/about"
  weight = 40

[[main]]
  name = "文件组织说明"
  pageRef = "/instruction"
  weight = 45

[[main]]
  identifier = "github"
  name = "GitHub"
  url = "https://github.com/gentoo-zh"
  weight = 50
