[[main]]
  name = "下載"
  pageRef = "/download"
  weight = 10

[[main]]
  name = "Overlay"
  pageRef = "/overlay"
  weight = 20

[[main]]
  name = "鏡像列表"
  pageRef = "/mirrorlist"
  weight = 30

[[main]]
  name = "更多"
  identifier = "more"
  weight = 40

[[main]]
  name = "類別"
  pageRef = "/categories"
  parent = "more"
  weight = 41

[[main]]
  name = "貢獻者列表"
  pageRef = "/contributors"
  parent = "more"
  weight = 42

[[main]]
  name = "貢獻指南"
  pageRef = "/contributing"
  parent = "more"
  weight = 43

[[main]]
  name = "關於"
  pageRef = "/about"
  parent = "more"
  weight = 44

[[main]]
  name = "更新記錄"
  pageRef = "/changelog"
  parent = "more"
  weight = 45

[[main]]
  identifier = "github"
  pre = "github"
  url = "https://github.com/gentoo-zh/gentoo-zh.github.com"
  weight = 50
